#!/usr/bin/env python3
"""Promote quarantine evolution records into ECC-KB capsules.

This MVP promotion gate is conservative:
- successful hidden-correct runs with speedup become candidate performance capsules;
- repeated failures become candidate/stable failure-signature capsules;
- stable promotion still requires manual review or additional multi-run evidence.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
from typing import Any

from ecc_utils import iter_json_files, read_json, safe_id, short_hash, utc_now, write_json


def get_nested(data: dict[str, Any], path: str, default: Any = None) -> Any:
    cur: Any = data
    for key in path.split("."):
        if not isinstance(cur, dict):
            return default
        cur = cur.get(key)
    return default if cur is None else cur


def hidden_passed(record: dict[str, Any]) -> bool:
    if record.get("final_decision") == "KEEP":
        return True
    for event in record.get("phase_events", []):
        status = get_nested(event, "correctness.hidden.status")
        if str(status).lower() in ("pass", "passed", "true", "1"):
            return True
    return False


def best_speedup(record: dict[str, Any]) -> float:
    values = []
    for event in record.get("phase_events", []):
        bench = event.get("benchmark", {}) if isinstance(event.get("benchmark"), dict) else {}
        for key in ("speedup_vs_eager_p50", "speedup_vs_torch_compile_p50"):
            try:
                values.append(float(bench.get(key, 0.0) or 0.0))
            except (TypeError, ValueError):
                pass
    return max(values) if values else 0.0


def diagnosis(record: dict[str, Any]) -> str:
    for event in reversed(record.get("phase_events", [])):
        text = str(event.get("diagnosis") or event.get("result") or "").strip()
        if text:
            return text
    return str(record.get("decision_rationale") or record.get("final_decision") or "unknown")


def base_capsule(record: dict[str, Any], unit_id: str, unit_type: str, status: str, phases: list[str], action_kind: str) -> dict[str, Any]:
    now = utc_now()
    task = record.get("task", {})
    backend = record.get("backend_fingerprint", {})
    return {
        "id": unit_id,
        "schema_version": "0.1",
        "unit_type": unit_type,
        "status": status,
        "abstraction_level": "backend_instance" if unit_type in {"optimization_motif", "tuning_record"} else "backend_abstract",
        "task_phases": phases,
        "operator_scope": {
            "families": [str(task.get("op_family", "unknown"))],
            "op_names": [str(task.get("op_name", ""))],
            "shape_patterns": [str(s) for s in task.get("shapes", [])],
            "dtype_scope": [str(d) for d in task.get("dtypes", [])],
            "layout_scope": ["as_declared_by_task"],
        },
        "backend_abstract_features": {"profile_symptoms": []},
        "backend_instances": [
            {
                "vendor": str(backend.get("vendor", "unknown")),
                "backend": str(backend.get("backend", "unknown")),
                "device_class": str(backend.get("device_class", "runtime_detected")),
                "target_fingerprint": short_hash(backend),
                "toolchain": backend.get("toolchain", {}),
                "validity": "verified" if record.get("final_decision") == "KEEP" else "requires_revalidation",
                "notes": "Generated by tools/promote_capsule.py from an H20 MVP evolution record.",
            }
        ],
        "conditions": {
            "valid_when": ["op family, dtype, shape bucket, backend fingerprint match the evidence"],
            "invalid_when": ["target fingerprint differs without revalidation", "hidden correctness has not passed"],
            "preconditions": ["schema gate passed"],
            "conflicts_with": [],
        },
        "mechanism": "Derived from a recorded compile/correctness/benchmark trajectory.",
        "action": {"kind": action_kind, "instructions": []},
        "expected_effect": {"correctness": "see validation gates", "performance": "see evidence", "search_efficiency": "reduce repeated invalid attempts", "risk": "requires revalidation outside recorded conditions"},
        "evidence": {"source_refs": [str(record.get("run_id"))], "run_ids": [str(record.get("run_id"))], "evidence_level": "single_run", "confidence": 0.5},
        "validation": {"gates": ["schema", "compile", "hidden_correctness", "anti_cheating", "benchmark_repeat", "reproducibility"], "correctness_matrix": ["smoke", "quick", "hidden"], "performance_requirements": ["p50/p95 benchmark recorded"], "promotion_policy": "MVP promotion; manual review recommended before stable use"},
        "failure_boundary": {"known_failures": [], "boundary_tests": ["held-out shape", "dtype matrix"], "do_not_apply": ["different backend without revalidation"]},
        "migration": {"transfer_policy": "requires_revalidation", "portable_part": ["root-cause category", "validation gate"], "replace_on_new_backend": ["knobs", "target fingerprint", "profiler mapping"]},
        "retrieval": {"keys": [safe_id(str(task.get("op_family", "unknown"))), safe_id(str(task.get("op_name", "")))], "negative_keys": [], "priority": 50, "max_context_tokens": 220},
        "lineage": {"created_by": "tools/promote_capsule.py", "created_at": now, "updated_at": now, "parent_units": record.get("used_capsules", []), "audit_log_refs": [str(record.get("artifacts", {}).get("workspace_uri", ""))]},
    }


def performance_capsule(record: dict[str, Any], min_speedup: float) -> dict[str, Any] | None:
    speed = best_speedup(record)
    if record.get("final_decision") != "KEEP" or not hidden_passed(record) or speed < min_speedup:
        return None
    task = record.get("task", {})
    unit_id = safe_id(f"perf_{task.get('op_family','op')}_{short_hash(record)}")
    cap = base_capsule(record, unit_id, "optimization_motif", "candidate", ["performance_optimize", "autotune"], "tune")
    cap["action"]["instructions"] = ["Use the successful candidate's schedule/knob pattern as a warm start.", "Retune only declared knobs for the current shape bucket.", "Keep hidden correctness and p95 latency as hard gates."]
    cap["expected_effect"]["performance"] = f"Observed best speedup {speed:.3f} in the source run."
    cap["evidence"].update({"benchmark_refs": [str(record.get("artifacts", {}).get("benchmark_json", ""))], "profile_refs": [str(record.get("artifacts", {}).get("profile_json", ""))]})
    cap["retrieval"]["keys"].extend(["performance", "tune", "h20"])
    return cap


def failure_capsule(signature: str, records: list[dict[str, Any]], stable_threshold: int) -> dict[str, Any]:
    first = records[0]
    task = first.get("task", {})
    unit_id = safe_id(f"fail_{task.get('op_family','op')}_{short_hash(signature)}")
    status = "stable" if len(records) >= stable_threshold else "candidate"
    cap = base_capsule(first, unit_id, "failure_signature", status, ["compile_repair", "correctness_repair", "retrospective"], "repair")
    cap["action"]["instructions"] = [f"Check for this failure signature: {signature[:240]}", "Return to OpSpec and boundary tests before performance tuning.", "Do not repeat the same edit unless the failing condition changed."]
    cap["failure_boundary"]["known_failures"] = [signature[:240]]
    cap["evidence"]["source_refs"] = [str(r.get("run_id")) for r in records]
    cap["evidence"]["run_ids"] = [str(r.get("run_id")) for r in records]
    cap["evidence"]["evidence_level"] = "multi_run" if len(records) >= stable_threshold else "single_run"
    cap["retrieval"]["keys"].extend([safe_id(signature), "failure", "repair"])
    cap["retrieval"]["priority"] = 70 if status == "stable" else 45
    return cap


def validate_capsule(capsule: dict[str, Any], schema: dict[str, Any] | None) -> list[str]:
    if not schema:
        return []
    try:
        import jsonschema  # type: ignore
    except Exception:
        return []
    validator = jsonschema.Draft202012Validator(schema)
    return [f"{'/'.join(str(p) for p in e.path) or '<root>'}: {e.message}" for e in validator.iter_errors(capsule)]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--quarantine", action="append", default=[])
    parser.add_argument("--failures", default=None)
    parser.add_argument("--schema", default="schemas/knowledge_unit.schema.json")
    parser.add_argument("--backend", default=None)
    parser.add_argument("--out", required=True)
    parser.add_argument("--report", required=True)
    parser.add_argument("--min-speedup", type=float, default=1.05)
    parser.add_argument("--stable-failure-threshold", type=int, default=2)
    args = parser.parse_args()

    records = []
    for path in iter_json_files(args.quarantine):
        try:
            record = read_json(path)
            if isinstance(record, dict) and "run_id" in record:
                records.append(record)
        except Exception:
            pass

    schema = read_json(args.schema, default=None) if args.schema else None
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    created: list[tuple[str, str, str]] = []
    rejected: list[str] = []

    for record in records:
        cap = performance_capsule(record, args.min_speedup)
        if not cap:
            continue
        errors = validate_capsule(cap, schema)
        if errors:
            rejected.append(f"{record.get('run_id')}: {'; '.join(errors[:5])}")
            continue
        write_json(out_dir / f"{cap['id']}.json", cap)
        created.append((cap["id"], cap["unit_type"], cap["status"]))

    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        if record.get("final_decision") == "FAIL":
            key = f"{record.get('task', {}).get('op_family', 'unknown')}::{diagnosis(record)[:200]}"
            groups[key].append(record)

    for key, group in groups.items():
        _, sig = key.split("::", 1)
        cap = failure_capsule(sig, group, args.stable_failure_threshold)
        errors = validate_capsule(cap, schema)
        if errors:
            rejected.append(f"{key}: {'; '.join(errors[:5])}")
            continue
        write_json(out_dir / f"{cap['id']}.json", cap)
        created.append((cap["id"], cap["unit_type"], cap["status"]))

    lines = ["# ECC-KB Promotion Report", "", f"- quarantine_records: {len(records)}", f"- created_capsules: {len(created)}", f"- rejected_candidates: {len(rejected)}", f"- min_speedup: {args.min_speedup}", "", "## Created capsules", ""]
    lines += [f"- `{cid}`: `{typ}`, status=`{status}`" for cid, typ, status in created]
    if rejected:
        lines += ["", "## Rejected promotion candidates", ""] + [f"- {item}" for item in rejected]
    Path(args.report).parent.mkdir(parents=True, exist_ok=True)
    Path(args.report).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"created={len(created)} rejected={len(rejected)} report={args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
